# Generated by Django 5.1.5 on 2025-01-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptin',
            new_name='description',
        ),
    ]
