# Generated by Django 4.1 on 2025-01-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_data',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_test',
            new_name='question_text',
        ),
    ]
